# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ana Paula Tello / UI + Diseño Visual
email: ana.tello@pm.me
description: > # this means to ignore newlines until "baseurl:"
 Diseñadora de productos digitales viviendo en la Ciudad de México. Me motiva la posibilidad de crear productos digitales que tengan un impacto positivo en las vidas de las personas que los usan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ana.tello.design" # the base hostname & protocol for your site
twitter_username: gacelita
github_username:  gacela

# Build settings
markdown: kramdown
